//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMS_2_0.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class SMS_Tbl_Login
    {
        public int Login_Id { get; set; }
        public int Login_Roll_Id { get; set; }

        [Required (ErrorMessage ="Please enter User Nane")]
        public string Login_UserName { get; set; }

        [Required (ErrorMessage = "Please enter Password")]
        public string User_Password { get; set; }
    }
}
